"""
EcoEye Cryptography & Security Engine.
Implements AES-256-GCM authenticated encryption with PBKDF2-HMAC-SHA256 key derivation,
secure nonce generation, and SHA-256 batch integrity verification for biomedical privacy.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
from typing import Any, Dict, Optional, Tuple, Union

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend

from ecoeye.config import settings


class SecurityError(Exception):
    """Base exception for security operations."""
    pass


class DecryptionError(SecurityError):
    """Raised when ciphertext authentication or decryption fails."""
    pass


class SecurityIntegrityError(SecurityError):
    """Raised when HMAC or payload integrity checksum mismatch occurs."""
    pass


class CryptoEngine:
    """
    AES-256-GCM authenticated encryption engine for offline SQLite biomedical records.
    Envelope format:
        [16 bytes SALT] + [12 bytes NONCE] + [16 bytes GCM TAG] + [CIPHERTEXT]
    Encoded as Base64 when represented as string.
    """

    SALT_SIZE = 16
    NONCE_SIZE = 12
    TAG_SIZE = 16
    KEY_SIZE = 32  # 256 bits

    def __init__(self, master_password: Optional[str] = None, iterations: Optional[int] = None):
        self.master_password = master_password or settings.SECURITY_ENCRYPTION_KEY
        self.iterations = iterations or settings.SECURITY_KEY_DERIVATION_ITERATIONS

    def _derive_key(self, salt: bytes) -> bytes:
        """Derive a 256-bit AES key from master password and unique per-record salt."""
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=self.KEY_SIZE,
            salt=salt,
            iterations=self.iterations,
            backend=default_backend(),
        )
        return kdf.derive(self.master_password.encode("utf-8"))

    def encrypt_bytes(self, plaintext: bytes, associated_data: Optional[bytes] = None) -> bytes:
        """
        Encrypt raw bytes using AES-256-GCM.
        Returns binary packed blob: salt (16) + nonce (12) + ciphertext_with_tag.
        Note: cryptography.AESGCM appends the 16-byte tag to the ciphertext automatically.
        """
        salt = os.urandom(self.SALT_SIZE)
        nonce = os.urandom(self.NONCE_SIZE)
        key = self._derive_key(salt)
        aesgcm = AESGCM(key)

        ciphertext_and_tag = aesgcm.encrypt(nonce, plaintext, associated_data)
        # Formato empaquetado: salt + nonce + (ciphertext + tag)
        return salt + nonce + ciphertext_and_tag

    def decrypt_bytes(self, payload: bytes, associated_data: Optional[bytes] = None) -> bytes:
        """
        Decrypt a binary packed payload generated by encrypt_bytes.
        """
        min_len = self.SALT_SIZE + self.NONCE_SIZE + self.TAG_SIZE
        if len(payload) < min_len:
            raise DecryptionError(f"Payload too short ({len(payload)} bytes, min {min_len})")

        salt = payload[:self.SALT_SIZE]
        nonce = payload[self.SALT_SIZE:self.SALT_SIZE + self.NONCE_SIZE]
        ciphertext_and_tag = payload[self.SALT_SIZE + self.NONCE_SIZE:]

        try:
            key = self._derive_key(salt)
            aesgcm = AESGCM(key)
            return aesgcm.decrypt(nonce, ciphertext_and_tag, associated_data)
        except Exception as e:
            raise DecryptionError("Decryption failed: corrupted payload or invalid key/tag") from e

    def encrypt_string(self, text: str, associated_data: Optional[bytes] = None) -> str:
        """
        Encrypt a UTF-8 string and return a Base64-encoded string representation.
        """
        raw_bytes = text.encode("utf-8")
        encrypted_bytes = self.encrypt_bytes(raw_bytes, associated_data=associated_data)
        return base64.b64encode(encrypted_bytes).decode("ascii")

    def decrypt_string(self, encrypted_b64: str, associated_data: Optional[bytes] = None) -> str:
        """
        Decrypt a Base64-encoded string into its original UTF-8 string.
        """
        try:
            raw_bytes = base64.b64decode(encrypted_b64.encode("ascii"))
        except Exception as e:
            raise DecryptionError("Invalid Base64 payload encoding") from e

        decrypted_bytes = self.decrypt_bytes(raw_bytes, associated_data=associated_data)
        try:
            return decrypted_bytes.decode("utf-8")
        except Exception as e:
            raise DecryptionError("Failed to decode decrypted bytes as UTF-8 string") from e

    def encrypt_dict(self, data: Dict[str, Any]) -> str:
        """Alias for encrypt_json for dictionary payloads."""
        return self.encrypt_json(data)

    def decrypt_dict(self, encrypted_b64: str) -> Dict[str, Any]:
        """Alias for decrypt_json returning a dictionary."""
        result = self.decrypt_json(encrypted_b64)
        if not isinstance(result, dict):
            raise DecryptionError(f"Decrypted payload is not a dict (got {type(result)})")
        return result

    def encrypt_json(self, data: Union[Dict[str, Any], list, str, int, float]) -> str:
        """
        Serialize any JSON-compatible object, encrypt it, and return a Base64 encoded string.
        """
        raw_json = json.dumps(data, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
        encrypted_bytes = self.encrypt_bytes(raw_json)
        return base64.b64encode(encrypted_bytes).decode("ascii")

    def decrypt_json(self, encrypted_b64: str) -> Any:
        """
        Decode a Base64 string, decrypt via AES-256-GCM, and parse the JSON.
        """
        try:
            raw_bytes = base64.b64decode(encrypted_b64.encode("ascii"))
        except Exception as e:
            raise DecryptionError("Invalid Base64 payload encoding") from e

        decrypted_bytes = self.decrypt_bytes(raw_bytes)
        try:
            return json.loads(decrypted_bytes.decode("utf-8"))
        except Exception as e:
            raise DecryptionError("Failed to deserialize decrypted JSON string") from e

    @staticmethod
    def compute_sha256(data: Union[str, bytes]) -> str:
        """Compute SHA-256 hex digest of data."""
        if isinstance(data, str):
            data = data.encode("utf-8")
        return hashlib.sha256(data).hexdigest()

    @staticmethod
    def compute_hmac_sha256(key: str, data: Union[str, bytes]) -> str:
        """Compute HMAC-SHA256 signature for sync batch integrity."""
        if isinstance(data, str):
            data = data.encode("utf-8")
        return hmac.new(key.encode("utf-8"), data, hashlib.sha256).hexdigest()

    @staticmethod
    def verify_hmac(key: str, data: Union[str, bytes], expected_signature: str) -> bool:
        """Constant-time verification of HMAC signature."""
        computed = CryptoEngine.compute_hmac_sha256(key, data)
        return hmac.compare_digest(computed, expected_signature)


# Module-level convenience functions matching standard cryptographic signatures
def compute_sha256(data: Union[str, bytes]) -> str:
    """Compute SHA-256 hex digest."""
    return CryptoEngine.compute_sha256(data)


def compute_hmac(data: Union[str, bytes], key: str) -> str:
    """Compute HMAC-SHA256 hex digest."""
    return CryptoEngine.compute_hmac_sha256(key=key, data=data)


def verify_hmac(data: Union[str, bytes], signature: str, key: str) -> bool:
    """Constant-time HMAC-SHA256 verification."""
    return CryptoEngine.verify_hmac(key=key, data=data, expected_signature=signature)


# Global singleton instance configured with app settings
crypto_engine = CryptoEngine()
